FROM learninglayers/tomcat
MAINTAINER Aarij Siddiqui <siddiqui ÄT dbis.rwth-aachen.de>

# Add the war from Jenkins
ADD https://github.com/learning-layers/Cloud-Video-Transcoder/releases/download/v0.4.0/clvitra-v0.4.0.war ${TOMCAT_HOME}/webapps/clvitra.war
